variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - test
  - upload
  - update-docs

default:
  image: firexstuff/firex-alpine-build:3.9.10
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install --upgrade firexbuilder

build:
  stage: build
  script:
    - firex-build build
  artifacts:
    paths:
      - dist/

build-docs:
  stage:  test
  script:
    - firex-build docs
  artifacts:
    paths:
      - html/  

test:
  stage: test
  script:
    - firex-build unit_tests
  artifacts:
    paths:
      - .coverage

#test-firexapp:
#  stage: test
#  trigger:
#    strategy: depend
#    project: FireXStuff/firexapp

upload-pkg:
  stage: upload
  script: 
    - pip install keyrings.alt
    - firex-build upload_pip
  only:
    - tags

upload-codecov:
  stage: upload
  script:
    - firex-build upload_codecov
  artifacts:
    reports:
      cobertura: coverage.xml

update-docs:
  inherit:
    default: false
  stage: update-docs
  image: google/cloud-sdk
  script:
    - gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS 
    - gsutil -m rsync -r html gs://www.firexstuff.com/firexkit
  needs:
    - upload-pkg
    - build-docs
  only:
    - tags

