
steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/FireXStuff/firexkit.git']
  dir: '$BUILD_ID'
- name: gcr.io/$PROJECT_ID/firex-alpine-build
  #args: ['python3', 'build.py', 'all', '--sudo',  '--output_dir', '/home/firex', '--upload_pip_if_tag', '--upload_codecov', '--skip_htmlcov']
  args: ['sh', '-c', 'sudo pip3 install firexbuilder && firex-build all --sudo --output_dir /home/firex --upload_pip_if_tag --upload_codecov --skip_htmlcov']
  dir: '$BUILD_ID/firexkit'
  secretEnv: ['TWINE_PASSWORD']
- name: gcr.io/cloud-builders/gsutil
  args: ['rsync', '-r', 'html', 'gs://www.firexkit.com']
  dir: '$BUILD_ID/firexkit'

secrets:
- kmsKeyName: projects/firex-kit-documentation/locations/global/keyRings/secrets/cryptoKeys/TWINE_PASSWORD
  secretEnv:
    TWINE_PASSWORD: 'CiQAI+bsJWZL0S/bFCabcznzcBMmAhWgs5e2gXI2Yi9nyfhWxm4SOQDnI0hgaoMJolUfZg9GZKnq2RA/Im2ZhFBIqcXkNpr/dEBuFBLIJFWjnXCHTR4jlQ+8s8GwECRbQw=='
