
steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/FireXStuff/firexkit.git']
  dir: '$BUILD_ID'
- name: gcr.io/$PROJECT_ID/firex-alpine-build
  args: ['python3', 'build.py', '--upload_pip_if_tag', '--upload_codecov', '--skip_htmlcov']
  dir: '$BUILD_ID/firexkit'
  secretEnv: ['TWINE_PASSWORD']

artifacts:
  objects:
    location: 'gs://www.firexkit.com'
    paths: ['$BUILD_ID/firexkit/html/']

secrets:
- kmsKeyName: projects/firex-kit-documentation/locations/global/keyRings/secrets/cryptoKeys/TWINE_PASSWORD
  secretEnv:
    TWINE_PASSWORD: 'CiQAI+bsJfbKBVxA+tOJAGnHIJRG0zFyUbzjvBx3S0BSF0T3UdUSOgDnI0hgPR5iY1f1pYZJUaPASEjviB8mzBIlAEI0LSMy+r9FUOIKIPDTO4lQN8BWsq3ksNAhe8f5aKA='
