name: firexkit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    working-directory: /home/firex
    
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3    
  Build:
    runs-on: ubuntu-latest
    container: firexstuff/firex-alpine-build:3.9.10
    steps:
      - name: Create venv
        run: |
          ls -alrt /
          echo $env
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
      - name: Install firexbuilder
        run: |
          pip install --upgrade firexbuilder
      - name: Build
        run: |
          firex-build build
